# Generated by Django 4.2.11 on 2024-08-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Иван', max_length=50)),
                ('surname', models.CharField(default='Иванов', max_length=50)),
                ('birthday', models.DateField()),
                ('email', models.CharField(default='ivanov@gmail.com', max_length=50)),
                ('password', models.CharField(default='********', max_length=50)),
            ],
        ),
    ]
